logging:
  level:
    root: INFO

job:
   zkConfig:
         zkConnectString: 127.0.0.1:2181
         rootPath: /lm-tbschedule/local
         zkSessionTimeout: 60000
         userName: admin
         password: admin
         isCheckParentPath: true

